# Generated by Django 3.0.1 on 2020-04-20 14:02

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Facts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='link',
            managers=[
                ('with_votes', django.db.models.manager.Manager()),
            ],
        ),
    ]
