# Generated by Django 3.0.1 on 2020-04-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facts', '0002_auto_20200420_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
