# Generated by Django 3.0.1 on 2020-04-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facts', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='HeadLines'),
        ),
    ]
